version: "3.8"

services:
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=bytesme
            - DB_USERNAME=bytesme
            - DB_PASSWORD=password
        depends_on:
            - db

    db:
        image: postgres:14
        environment:
            POSTGRES_DB: bytesme
            POSTGRES_USER: bytesme
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
